export const PUBLIC_ROUTE = 'unicrm:public-route';
export const REQUIRED_PERMISSIONS = 'unicrm:required-permissions';

export const PERMISSIONS = {
  dashboardRead: 'dashboard.read',
  reportsRead: 'reports.read',
  notificationsRead: 'notifications.read',
  activityCreate: 'activity.create',
  activityRead: 'activity.read',
  automationManage: 'automation.manage',
  automationRead: 'automation.read',
  automationRetry: 'automation.retry',
  automationRunsRead: 'automation.runs.read',
  emailRead: 'email.read',
  emailSend: 'email.send',
  emailTemplateRead: 'email_template.read',
  emailTemplateManage: 'email_template.manage',
  mailboxRead: 'mailbox.read',
  mailboxManage: 'mailbox.manage',
  mailRead: 'mail.read',
  mailSend: 'mail.send',
  mailLink: 'mail.link',
  companyCreate: 'company.create',
  companyBulkUpdate: 'company.bulk_update',
  companyDelete: 'company.delete',
  companyRead: 'company.read',
  companyUpdate: 'company.update',
  contactCreate: 'contact.create',
  contactBulkUpdate: 'contact.bulk_update',
  contactDelete: 'contact.delete',
  contactRead: 'contact.read',
  contactUpdate: 'contact.update',
  customFieldManage: 'custom_field.manage',
  customFieldRead: 'custom_field.read',
  dataDuplicatesRead: 'data.duplicates.read',
  dataExport: 'data.export',
  dataImport: 'data.import',
  dataMerge: 'data.merge',
  integrationRead: 'integration.read',
  integrationManage: 'integration.manage',
  integrationLogsRead: 'integration.logs.read',
  integrationRetry: 'integration.retry',
  webhookManage: 'webhook.manage',
  leadAssign: 'lead.assign',
  leadBulkUpdate: 'lead.bulk_update',
  leadCreate: 'lead.create',
  leadDelete: 'lead.delete',
  leadRead: 'lead.read',
  leadStageUpdate: 'lead.stage.update',
  leadUpdate: 'lead.update',
  pipelineManage: 'pipeline.manage',
  pipelineRead: 'pipeline.read',
  projectCreate: 'project.create',
  projectBulkUpdate: 'project.bulk_update',
  projectDelete: 'project.delete',
  projectManageMembers: 'project.manage_members',
  projectRead: 'project.read',
  projectUpdate: 'project.update',
  taskCreate: 'task.create',
  taskBulkUpdate: 'task.bulk_update',
  taskRead: 'task.read',
  taskUpdate: 'task.update',
  taskDelete: 'task.delete',
  taskAssign: 'task.assign',
  taskCommentCreate: 'task.comment.create',
  taskCommentRead: 'task.comment.read',
  attachmentCreate: 'attachment.create',
  attachmentRead: 'attachment.read',
  attachmentDelete: 'attachment.delete',
  quotationCreate: 'quotation.create',
  quotationRead: 'quotation.read',
  quotationUpdate: 'quotation.update',
  quotationDelete: 'quotation.delete',
  quotationSend: 'quotation.send',
  quotationAccept: 'quotation.accept',
  quotationReject: 'quotation.reject',
  paymentCreate: 'payment.create',
  paymentRead: 'payment.read',
  paymentUpdate: 'payment.update',
  paymentDelete: 'payment.delete',
  roleManage: 'role.manage',
  roleRead: 'role.read',
  securitySessionsRead: 'security.sessions.read',
  securitySessionsRevoke: 'security.sessions.revoke',
  settingsRead: 'settings.read',
  settingsUpdate: 'settings.update',
  savedViewCreate: 'saved_view.create',
  savedViewDelete: 'saved_view.delete',
  savedViewRead: 'saved_view.read',
  savedViewUpdate: 'saved_view.update',
  tagManage: 'tag.manage',
  tagRead: 'tag.read',
  userDisable: 'user.disable',
  userInvite: 'user.invite',
  userRead: 'user.read',
  userUpdate: 'user.update',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: ReadonlyArray<{ key: PermissionKey; description: string }> = [
  { key: PERMISSIONS.dashboardRead, description: 'View the operational dashboard' },
  { key: PERMISSIONS.reportsRead, description: 'View operational reports' },
  { key: PERMISSIONS.notificationsRead, description: 'View personal notifications' },
  { key: PERMISSIONS.automationRead, description: 'View automation rules' },
  { key: PERMISSIONS.automationManage, description: 'Create and manage automation rules' },
  { key: PERMISSIONS.automationRunsRead, description: 'View automation run history' },
  { key: PERMISSIONS.automationRetry, description: 'Retry eligible failed automation runs' },
  { key: PERMISSIONS.emailRead, description: 'View CRM email history and messages' },
  { key: PERMISSIONS.emailSend, description: 'Send CRM email' },
  { key: PERMISSIONS.emailTemplateRead, description: 'View email templates and sending identity' },
  {
    key: PERMISSIONS.emailTemplateManage,
    description: 'Manage email templates and sending identity',
  },
  { key: PERMISSIONS.mailboxRead, description: 'View organization mailbox connections' },
  { key: PERMISSIONS.mailboxManage, description: 'Manage organization mailbox connections' },
  { key: PERMISSIONS.mailRead, description: 'View synchronized mailbox messages and threads' },
  { key: PERMISSIONS.mailSend, description: 'Send and reply through connected mailboxes' },
  { key: PERMISSIONS.mailLink, description: 'Link mailbox threads to CRM records' },
  { key: PERMISSIONS.companyCreate, description: 'Create companies' },
  { key: PERMISSIONS.companyBulkUpdate, description: 'Bulk update companies' },
  { key: PERMISSIONS.companyRead, description: 'View companies' },
  { key: PERMISSIONS.companyUpdate, description: 'Update companies' },
  { key: PERMISSIONS.companyDelete, description: 'Archive companies' },
  { key: PERMISSIONS.contactCreate, description: 'Create contacts' },
  { key: PERMISSIONS.contactBulkUpdate, description: 'Bulk update contacts' },
  { key: PERMISSIONS.contactRead, description: 'View contacts' },
  { key: PERMISSIONS.contactUpdate, description: 'Update contacts' },
  { key: PERMISSIONS.contactDelete, description: 'Archive contacts' },
  { key: PERMISSIONS.customFieldRead, description: 'View custom field definitions and values' },
  { key: PERMISSIONS.customFieldManage, description: 'Manage custom field definitions' },
  { key: PERMISSIONS.dataImport, description: 'Import CRM records from reviewed CSV files' },
  { key: PERMISSIONS.dataExport, description: 'Export permitted CRM records to CSV' },
  { key: PERMISSIONS.dataDuplicatesRead, description: 'Review possible duplicate CRM records' },
  { key: PERMISSIONS.dataMerge, description: 'Merge duplicate company and contact records' },
  { key: PERMISSIONS.integrationRead, description: 'View integration connections and mappings' },
  {
    key: PERMISSIONS.integrationManage,
    description: 'Manage integration connections and mappings',
  },
  {
    key: PERMISSIONS.integrationLogsRead,
    description: 'View integration events and webhook deliveries',
  },
  {
    key: PERMISSIONS.integrationRetry,
    description: 'Retry failed integration events and deliveries',
  },
  { key: PERMISSIONS.webhookManage, description: 'Manage outbound webhook subscriptions' },
  { key: PERMISSIONS.leadCreate, description: 'Create leads' },
  { key: PERMISSIONS.leadBulkUpdate, description: 'Bulk update leads' },
  { key: PERMISSIONS.leadRead, description: 'View leads' },
  { key: PERMISSIONS.leadUpdate, description: 'Update leads' },
  { key: PERMISSIONS.leadDelete, description: 'Archive leads' },
  { key: PERMISSIONS.leadAssign, description: 'Assign lead owners' },
  { key: PERMISSIONS.leadStageUpdate, description: 'Move leads between pipeline stages' },
  { key: PERMISSIONS.activityCreate, description: 'Create lead activities and follow-ups' },
  { key: PERMISSIONS.activityRead, description: 'View lead activities and follow-ups' },
  { key: PERMISSIONS.pipelineRead, description: 'View sales pipelines' },
  { key: PERMISSIONS.pipelineManage, description: 'Manage sales pipelines' },
  { key: PERMISSIONS.tagRead, description: 'View and assign organization tags' },
  { key: PERMISSIONS.tagManage, description: 'Create, rename, and delete organization tags' },
  { key: PERMISSIONS.savedViewCreate, description: 'Create saved list views' },
  { key: PERMISSIONS.savedViewRead, description: 'View permitted saved list views' },
  { key: PERMISSIONS.savedViewUpdate, description: 'Update permitted saved list views' },
  { key: PERMISSIONS.savedViewDelete, description: 'Delete permitted saved list views' },
  { key: PERMISSIONS.projectCreate, description: 'Create projects' },
  { key: PERMISSIONS.projectBulkUpdate, description: 'Bulk update projects' },
  { key: PERMISSIONS.projectRead, description: 'View projects' },
  { key: PERMISSIONS.projectUpdate, description: 'Update projects' },
  { key: PERMISSIONS.projectDelete, description: 'Archive projects' },
  { key: PERMISSIONS.projectManageMembers, description: 'Manage project members' },
  { key: PERMISSIONS.taskCreate, description: 'Create tasks' },
  { key: PERMISSIONS.taskBulkUpdate, description: 'Bulk update tasks' },
  { key: PERMISSIONS.taskRead, description: 'View tasks' },
  { key: PERMISSIONS.taskUpdate, description: 'Update tasks' },
  { key: PERMISSIONS.taskDelete, description: 'Archive tasks' },
  { key: PERMISSIONS.taskAssign, description: 'Assign tasks' },
  { key: PERMISSIONS.taskCommentCreate, description: 'Comment on tasks' },
  { key: PERMISSIONS.taskCommentRead, description: 'View task comments' },
  { key: PERMISSIONS.attachmentCreate, description: 'Upload project and task files' },
  { key: PERMISSIONS.attachmentRead, description: 'View project and task files' },
  { key: PERMISSIONS.attachmentDelete, description: 'Delete project and task files' },
  { key: PERMISSIONS.quotationCreate, description: 'Create quotations' },
  { key: PERMISSIONS.quotationRead, description: 'View quotations and PDFs' },
  { key: PERMISSIONS.quotationUpdate, description: 'Update draft quotations' },
  { key: PERMISSIONS.quotationDelete, description: 'Archive draft quotations' },
  { key: PERMISSIONS.quotationSend, description: 'Mark quotations as sent' },
  { key: PERMISSIONS.quotationAccept, description: 'Accept sent quotations' },
  { key: PERMISSIONS.quotationReject, description: 'Reject sent quotations' },
  { key: PERMISSIONS.paymentCreate, description: 'Record payments' },
  { key: PERMISSIONS.paymentRead, description: 'View payments' },
  { key: PERMISSIONS.paymentUpdate, description: 'Correct payments' },
  { key: PERMISSIONS.paymentDelete, description: 'Archive payments' },
  { key: PERMISSIONS.userRead, description: 'View organization users' },
  { key: PERMISSIONS.userInvite, description: 'Invite organization users' },
  { key: PERMISSIONS.userUpdate, description: 'Update organization users' },
  { key: PERMISSIONS.userDisable, description: 'Suspend or disable organization users' },
  { key: PERMISSIONS.roleRead, description: 'View roles and permissions' },
  { key: PERMISSIONS.roleManage, description: 'Create and update roles' },
  { key: PERMISSIONS.settingsRead, description: 'View organization settings' },
  { key: PERMISSIONS.settingsUpdate, description: 'Update organization settings' },
  { key: PERMISSIONS.securitySessionsRead, description: 'View personal sessions' },
  { key: PERMISSIONS.securitySessionsRevoke, description: 'Revoke personal sessions' },
];

export const DEFAULT_ROLES = ['Owner', 'Admin', 'Manager', 'Staff', 'Viewer'] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<(typeof DEFAULT_ROLES)[number], PermissionKey[]> = {
  Owner: PERMISSION_CATALOG.map(({ key }) => key),
  Admin: PERMISSION_CATALOG.map(({ key }) => key),
  Manager: [
    PERMISSIONS.dashboardRead,
    PERMISSIONS.reportsRead,
    PERMISSIONS.notificationsRead,
    PERMISSIONS.automationRead,
    PERMISSIONS.automationRunsRead,
    PERMISSIONS.emailRead,
    PERMISSIONS.emailSend,
    PERMISSIONS.emailTemplateRead,
    PERMISSIONS.mailboxRead,
    PERMISSIONS.mailRead,
    PERMISSIONS.mailSend,
    PERMISSIONS.mailLink,
    PERMISSIONS.companyCreate,
    PERMISSIONS.companyBulkUpdate,
    PERMISSIONS.companyRead,
    PERMISSIONS.companyUpdate,
    PERMISSIONS.contactCreate,
    PERMISSIONS.contactBulkUpdate,
    PERMISSIONS.contactRead,
    PERMISSIONS.contactUpdate,
    PERMISSIONS.dataImport,
    PERMISSIONS.dataExport,
    PERMISSIONS.dataDuplicatesRead,
    PERMISSIONS.dataMerge,
    PERMISSIONS.integrationRead,
    PERMISSIONS.integrationLogsRead,
    PERMISSIONS.integrationRetry,
    PERMISSIONS.leadCreate,
    PERMISSIONS.leadBulkUpdate,
    PERMISSIONS.leadRead,
    PERMISSIONS.leadUpdate,
    PERMISSIONS.leadAssign,
    PERMISSIONS.leadStageUpdate,
    PERMISSIONS.activityCreate,
    PERMISSIONS.activityRead,
    PERMISSIONS.pipelineRead,
    PERMISSIONS.customFieldRead,
    PERMISSIONS.tagRead,
    PERMISSIONS.savedViewCreate,
    PERMISSIONS.savedViewRead,
    PERMISSIONS.savedViewUpdate,
    PERMISSIONS.savedViewDelete,
    PERMISSIONS.projectCreate,
    PERMISSIONS.projectBulkUpdate,
    PERMISSIONS.projectRead,
    PERMISSIONS.projectUpdate,
    PERMISSIONS.projectDelete,
    PERMISSIONS.projectManageMembers,
    PERMISSIONS.taskCreate,
    PERMISSIONS.taskBulkUpdate,
    PERMISSIONS.taskRead,
    PERMISSIONS.taskUpdate,
    PERMISSIONS.taskDelete,
    PERMISSIONS.taskAssign,
    PERMISSIONS.taskCommentCreate,
    PERMISSIONS.taskCommentRead,
    PERMISSIONS.attachmentCreate,
    PERMISSIONS.attachmentRead,
    PERMISSIONS.attachmentDelete,
    PERMISSIONS.quotationCreate,
    PERMISSIONS.quotationRead,
    PERMISSIONS.quotationUpdate,
    PERMISSIONS.quotationDelete,
    PERMISSIONS.quotationSend,
    PERMISSIONS.quotationAccept,
    PERMISSIONS.quotationReject,
    PERMISSIONS.paymentCreate,
    PERMISSIONS.paymentRead,
    PERMISSIONS.paymentUpdate,
    PERMISSIONS.paymentDelete,
    PERMISSIONS.userRead,
    PERMISSIONS.roleRead,
    PERMISSIONS.settingsRead,
    PERMISSIONS.securitySessionsRead,
    PERMISSIONS.securitySessionsRevoke,
  ],
  Staff: [
    PERMISSIONS.dashboardRead,
    PERMISSIONS.reportsRead,
    PERMISSIONS.notificationsRead,
    PERMISSIONS.emailRead,
    PERMISSIONS.emailSend,
    PERMISSIONS.mailRead,
    PERMISSIONS.mailSend,
    PERMISSIONS.companyCreate,
    PERMISSIONS.companyBulkUpdate,
    PERMISSIONS.companyRead,
    PERMISSIONS.companyUpdate,
    PERMISSIONS.contactCreate,
    PERMISSIONS.contactBulkUpdate,
    PERMISSIONS.contactRead,
    PERMISSIONS.contactUpdate,
    PERMISSIONS.dataExport,
    PERMISSIONS.leadCreate,
    PERMISSIONS.leadBulkUpdate,
    PERMISSIONS.leadRead,
    PERMISSIONS.leadUpdate,
    PERMISSIONS.leadStageUpdate,
    PERMISSIONS.activityCreate,
    PERMISSIONS.activityRead,
    PERMISSIONS.pipelineRead,
    PERMISSIONS.customFieldRead,
    PERMISSIONS.tagRead,
    PERMISSIONS.savedViewCreate,
    PERMISSIONS.savedViewRead,
    PERMISSIONS.savedViewUpdate,
    PERMISSIONS.savedViewDelete,
    PERMISSIONS.projectCreate,
    PERMISSIONS.projectBulkUpdate,
    PERMISSIONS.projectRead,
    PERMISSIONS.projectUpdate,
    PERMISSIONS.taskCreate,
    PERMISSIONS.taskBulkUpdate,
    PERMISSIONS.taskRead,
    PERMISSIONS.taskUpdate,
    PERMISSIONS.taskAssign,
    PERMISSIONS.taskCommentCreate,
    PERMISSIONS.taskCommentRead,
    PERMISSIONS.attachmentCreate,
    PERMISSIONS.attachmentRead,
    PERMISSIONS.attachmentDelete,
    PERMISSIONS.quotationCreate,
    PERMISSIONS.quotationRead,
    PERMISSIONS.quotationUpdate,
    PERMISSIONS.paymentRead,
    PERMISSIONS.settingsRead,
    PERMISSIONS.securitySessionsRead,
    PERMISSIONS.securitySessionsRevoke,
  ],
  Viewer: [
    PERMISSIONS.dashboardRead,
    PERMISSIONS.reportsRead,
    PERMISSIONS.notificationsRead,
    PERMISSIONS.emailRead,
    PERMISSIONS.mailRead,
    PERMISSIONS.companyRead,
    PERMISSIONS.contactRead,
    PERMISSIONS.leadRead,
    PERMISSIONS.activityRead,
    PERMISSIONS.pipelineRead,
    PERMISSIONS.customFieldRead,
    PERMISSIONS.tagRead,
    PERMISSIONS.savedViewRead,
    PERMISSIONS.projectRead,
    PERMISSIONS.taskRead,
    PERMISSIONS.taskCommentRead,
    PERMISSIONS.attachmentRead,
    PERMISSIONS.quotationRead,
    PERMISSIONS.paymentRead,
    PERMISSIONS.settingsRead,
    PERMISSIONS.securitySessionsRead,
    PERMISSIONS.securitySessionsRevoke,
  ],
};
